#!/bin/bash
#yum update -y
#######################################################################################################################################################
### This bootstrap script does the following
### 1- install gluster packages on all nodes 
### 2- on glusterfs-server<X> nodes it formats the NVME disks (HighIO1.36 shape), creates a LVM LV called brick<X> (XFS)
### 3- fixes the resolve.conf file. GlusterFS needs DNS to work properly so make sure you update the below domains to match your environment
### 4- disable local firewall. Feel free to update this script to open only the required ports. I have a security list rule that allows communication
### within my tenancy (subnet Source: 172.0.0.0/16  IP Protocol: All Protocols Allows: all traffic for all ports
### 5- install and configure a gluster volume called glustervol1 using server1-brick1, server2-brick2 and server3-brick3 LVs (replicas)
### 6- creates a local mount point in the glusterFS clients
### 7- add a local entry in the clients Fstab with '_netdev' attribute. IMPORTANT to avoid boot issues.
### 
### Feel free to contact me in case of any questions - Gilson Melo - gilson.melo@oracle.com
######################################################################################################################################################
exec 2>/dev/null
glusterfshost=$(hostname -s)
case $glusterfshost in
	"glusterfs-server1")
		#!/bin/bash
		yum install -y centos-release-gluster310.noarch
		yum install -y glusterfs-server samba
		pvcreate /dev/nvme0n1
		pvcreate /dev/nvme1n1
		pvcreate /dev/nvme2n1
		pvcreate /dev/nvme3n1
		vgcreate vg_gluster /dev/nvme0n1 /dev/nvme1n1 /dev/nvme2n1 /dev/nvme3n1
		lvcreate -L 11.6T -n brick1 vg_gluster
		mkfs.xfs /dev/vg_gluster/brick1
		mkdir -p /bricks/brick1
		mount /dev/vg_gluster/brick1 /bricks/brick1
		echo "/dev/vg_gluster/brick1  /bricks/brick1    xfs     defaults,_netdev  0 0" >> /etc/fstab
		sed -i '/search/d' /etc/resolv.conf 
		echo "search baremetal.oraclevcn.com publicsubnetad2.baremetal.oraclevcn.com publicsubnetad1.baremetal.oraclevcn.com publicsubnetad3.baremetal.oraclevcn.com localdomain" >> /etc/resolv.conf
		chattr -R +i /etc/resolv.conf
		#firewall-cmd --zone=public --add-port=24007-24020/tcp --permanent
		#firewall-cmd --reload
		systemctl disable firewalld
		systemctl stop firewalld
		systemctl enable glusterd.service
		systemctl start glusterd.service
		mkdir /bricks/brick1/brick
		;;
	"glusterfs-server2")
        #!/bin/bash
        yum install -y centos-release-gluster310.noarch
        yum install -y glusterfs-server samba
        pvcreate /dev/nvme0n1
        pvcreate /dev/nvme1n1
        pvcreate /dev/nvme2n1
        pvcreate /dev/nvme3n1
        vgcreate vg_gluster /dev/nvme0n1 /dev/nvme1n1 /dev/nvme2n1 /dev/nvme3n1
        lvcreate -L 11.6T -n brick2 vg_gluster
        mkfs.xfs /dev/vg_gluster/brick2
        mkdir -p /bricks/brick2
        mount /dev/vg_gluster/brick2 /bricks/brick2
        echo "/dev/vg_gluster/brick2  /bricks/brick2    xfs     defaults,_netdev  0 0" >> /etc/fstab
        sed -i '/search/d' /etc/resolv.conf
        echo "search baremetal.oraclevcn.com publicsubnetad2.baremetal.oraclevcn.com publicsubnetad1.baremetal.oraclevcn.com publicsubnetad3.baremetal.oraclevcn.com localdomain" >> /etc/resolv.conf
        chattr -R +i /etc/resolv.conf
        #firewall-cmd --zone=public --add-port=24007-24020/tcp --permanent
        #firewall-cmd --reload
        systemctl disable firewalld
        systemctl stop firewalld
        systemctl enable glusterd.service
        systemctl start glusterd.service
        mkdir /bricks/brick2/brick
        ;;
	"glusterfs-server3")
		#!/bin/bash
        yum install -y centos-release-gluster310.noarch
        yum install -y glusterfs-server samba
        pvcreate /dev/nvme0n1
        pvcreate /dev/nvme1n1
        pvcreate /dev/nvme2n1
        pvcreate /dev/nvme3n1
        vgcreate vg_gluster /dev/nvme0n1 /dev/nvme1n1 /dev/nvme2n1 /dev/nvme3n1
        lvcreate -L 11.6T -n brick3 vg_gluster
        mkfs.xfs /dev/vg_gluster/brick3
        mkdir -p /bricks/brick3
        mount /dev/vg_gluster/brick3 /bricks/brick3
        echo "/dev/vg_gluster/brick3  /bricks/brick3    xfs     defaults,_netdev  0 0" >> /etc/fstab
		sed -i '/search/d' /etc/resolv.conf 
        echo "search baremetal.oraclevcn.com publicsubnetad2.baremetal.oraclevcn.com publicsubnetad1.baremetal.oraclevcn.com publicsubnetad3.baremetal.oraclevcn.com localdomain" >> /etc/resolv.conf
        chattr -R +i /etc/resolv.conf
        #firewall-cmd --zone=public --add-port=24007-24020/tcp --permanent
        #firewall-cmd --reload
        systemctl disable firewalld
        systemctl stop firewalld
		systemctl enable glusterd.service
        systemctl start glusterd.service
        mkdir /bricks/brick3/brick
		sleep 20
        export host3=`hostname`
        export server1=`host glusterfs-server1 |cut -c1-17`
        export server2=`host glusterfs-server2 |cut -c1-17`
		gluster peer probe $server1
		gluster peer probe $server2
		sleep 20
        gluster volume create glustervol1 replica 3 transport tcp $host3:/bricks/brick3/brick $server2:/bricks/brick2/brick $server1:/bricks/brick1/brick force
		sleep 10
        gluster volume start glustervol1
		;;
	"glusterfs-client1")
		sed -i '/search/d' /etc/resolv.conf 
        echo "search baremetal.oraclevcn.com publicsubnetad2.baremetal.oraclevcn.com publicsubnetad1.baremetal.oraclevcn.com publicsubnetad3.baremetal.oraclevcn.com localdomain" >> /etc/resolv.conf
        chattr -R +i /etc/resolv.conf
		#firewall-cmd --zone=public --add-port=111/tcp --add-port=139/tcp --add-port=445/tcp --add-port=965/tcp --add-port=2049/tcp \
		#--add-port=38465-38469/tcp --add-port=631/tcp --add-port=111/udp --add-port=963/udp --add-port=49152-49251/tcp  --permanent
		#firewall-cmd --reload
		systemctl disable firewalld
        systemctl stop firewalld
		yum install glusterfs glusterfs-fuse attr -y
		mkdir /mnt/glustervol1
		sleep 4m
        echo "glusterfs-server1:/glustervol1 /mnt/glustervol1	glusterfs defaults,_netdev  0 0" >> /etc/fstab
		mount -a
		;;
	"glusterfs-client2")
		sed -i '/search/d' /etc/resolv.conf
        echo "search baremetal.oraclevcn.com publicsubnetad2.baremetal.oraclevcn.com publicsubnetad1.baremetal.oraclevcn.com publicsubnetad3.baremetal.oraclevcn.com localdomain" >> /etc/resolv.conf
        chattr -R +i /etc/resolv.conf
        #firewall-cmd --zone=public --add-port=111/tcp --add-port=139/tcp --add-port=445/tcp --add-port=965/tcp --add-port=2049/tcp \
        #--add-port=38465-38469/tcp --add-port=631/tcp --add-port=111/udp --add-port=963/udp --add-port=49152-49251/tcp  --permanent
        #firewall-cmd --reload
		systemctl disable firewalld
        systemctl stop firewalld
        yum install glusterfs glusterfs-fuse attr -y
        mkdir /mnt/glustervol1
        sleep 4m
        echo "glusterfs-server2:/glustervol1 /mnt/glustervol1   glusterfs defaults,_netdev  0 0" >> /etc/fstab
        mount -a
        ;;
	"glusterfs-client3")
		sed -i '/search/d' /etc/resolv.conf
        echo "search baremetal.oraclevcn.com publicsubnetad2.baremetal.oraclevcn.com publicsubnetad1.baremetal.oraclevcn.com publicsubnetad3.baremetal.oraclevcn.com localdomain" >> /etc/resolv.conf
        chattr -R +i /etc/resolv.conf
        #firewall-cmd --zone=public --add-port=111/tcp --add-port=139/tcp --add-port=445/tcp --add-port=965/tcp --add-port=2049/tcp \
        #--add-port=38465-38469/tcp --add-port=631/tcp --add-port=111/udp --add-port=963/udp --add-port=49152-49251/tcp  --permanent
        #firewall-cmd --reload
		systemctl disable firewalld
        systemctl stop firewalld
        yum install glusterfs glusterfs-fuse attr -y
        mkdir /mnt/glustervol1
        sleep 4m
        echo "glusterfs-server3:/glustervol1 /mnt/glustervol1   glusterfs defaults,_netdev  0 0" >> /etc/fstab
        mount -a
        ;;
	*)
        echo "$glusterfshost" >>/tmp/notfound.txt
		;;
esac
